name: prod
on:
  push:
    branches:
      - master
jobs:
  prod:
    name: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - uses: werf/actions/install@v1.2
        with:
          kube-config-base64: ${{ secrets.KUBECONFIG_BASE64 }}
      - run: |
         . $(werf ci-env github --as-file)
          werf converge --repo amitmau07/newimage
        env:
          WERF_ENV: prod
